// Generated by smithy-ts-codegen — do not edit.

import { z } from 'zod'

// --- Data types ---

export const AlreadyExistsSchema = z.object({
  message: z.string(),
})
export type AlreadyExists = z.infer<typeof AlreadyExistsSchema>

export type Bytes = AsyncIterable<Uint8Array>

export const ConflictSchema = z.object({
  message: z.string(),
})
export type Conflict = z.infer<typeof ConflictSchema>

export const DoneSchema = z.object({
})
export type Done = z.infer<typeof DoneSchema>

export const FailureSchema = z.object({
  reason: z.string(),
})
export type Failure = z.infer<typeof FailureSchema>

export const GetPersonInputSchema = z.object({
  id: z.string(),
  verbose: z.boolean().optional(),
})
export type GetPersonInput = z.infer<typeof GetPersonInputSchema>

export const KindSchema = z.enum(['admin', 'user'])
export type Kind = z.infer<typeof KindSchema>

export const NotFoundSchema = z.object({
  message: z.string(),
})
export type NotFound = z.infer<typeof NotFoundSchema>

/**
 * A branded alias.
 */
export const PersonIdSchema = z.string().brand<'PersonId'>()
export type PersonId = z.infer<typeof PersonIdSchema>

export const ScoresSchema = z.record(z.string(), z.number().int())
export type Scores = z.infer<typeof ScoresSchema>

export const TagsSchema = z.array(z.string())
export type Tags = z.infer<typeof TagsSchema>

export const PlainOutputSchema = z.object({
  message: z.string(),
})
export type PlainOutput = z.infer<typeof PlainOutputSchema>

export const SearchInputSchema = z.object({
  q: z.string().optional(),
})
export type SearchInput = z.infer<typeof SearchInputSchema>

export const UploadOutputSchema = z.object({
  stored: z.number().int(),
})
export type UploadOutput = z.infer<typeof UploadOutputSchema>

export const WatchInputSchema = z.object({
  id: z.string(),
  since: z.coerce.date().optional(),
})
export type WatchInput = z.infer<typeof WatchInputSchema>

export const UploadInputSchema = z.object({
  id: z.string(),
})
export type UploadInput = z.infer<typeof UploadInputSchema> & { body: AsyncIterable<Uint8Array> }

export const PersonSchema = z.object({
  name: z.string(),
  age: z.number().int().optional(),
  kind: KindSchema,
  tags: TagsSchema.optional(),
  scores: ScoresSchema.optional(),
  id: PersonIdSchema.optional(),
  registered: z.coerce.date().optional(),
  active: z.boolean().optional(),
  payload: z.unknown().optional(),
})
export type Person = z.infer<typeof PersonSchema>

export const FeedEventSchema = z.union([
  z.object({ item: PersonSchema }),
  z.object({ completed: DoneSchema }),
  z.object({ failed: FailureSchema }),
])
export type FeedEvent = z.infer<typeof FeedEventSchema>

export const GetPersonOutputSchema = z.object({
  person: PersonSchema,
  trace: z.string().optional(),
  code: z.number().int().optional(),
})
export type GetPersonOutput = z.infer<typeof GetPersonOutputSchema>

export const PeopleSchema = z.array(PersonSchema)
export type People = z.infer<typeof PeopleSchema>

export const PutPersonInputSchema = z.object({
  id: z.string(),
  person: PersonSchema,
  ifMatch: z.string().optional(),
})
export type PutPersonInput = z.infer<typeof PutPersonInputSchema>

export const ShapeSchema = z.union([
  z.object({ person: PersonSchema }),
  z.object({ label: z.string() }),
])
export type Shape = z.infer<typeof ShapeSchema>

export const EchoInputSchema = z.object({
})
export type EchoInput = { incoming: AsyncIterable<FeedEvent> }

export const EchoOutputSchema = z.object({
})
export type EchoOutput = { outgoing: AsyncIterable<FeedEvent> }

export const WatchOutputSchema = z.object({
  session: z.string().optional(),
})
export type WatchOutput = z.infer<typeof WatchOutputSchema> & { events: AsyncIterable<FeedEvent> }

export const SearchOutputSchema = z.object({
  results: PeopleSchema,
})
export type SearchOutput = z.infer<typeof SearchOutputSchema>


// --- Error classes ---

export class AlreadyExistsError extends Error {
  readonly payload: AlreadyExists
  static readonly status = 409
  static readonly errorType = 'AlreadyExists'
  readonly status = 409
  readonly errorType = 'AlreadyExists'
  constructor(payload: AlreadyExists) {
    super(payload.message)
    this.name = 'AlreadyExistsError'
    this.payload = payload
  }
}

export class ConflictError extends Error {
  readonly payload: Conflict
  static readonly status = 409
  static readonly errorType = 'Conflict'
  readonly status = 409
  readonly errorType = 'Conflict'
  constructor(payload: Conflict) {
    super(payload.message)
    this.name = 'ConflictError'
    this.payload = payload
  }
}

export class NotFoundError extends Error {
  readonly payload: NotFound
  static readonly status = 404
  static readonly errorType = 'NotFound'
  readonly status = 404
  readonly errorType = 'NotFound'
  constructor(payload: NotFound) {
    super(payload.message)
    this.name = 'NotFoundError'
    this.payload = payload
  }
}


// --- Transport ---

/** Per-operation transport options. The generator threads these straight
 * through to `Transport.request` without inspecting them, so concrete
 * transports can layer in framework-specific knobs (e.g. axios's
 * `skipErrorPopup`) without the codegen having to know about them.
 */
export interface TransportOptions {
  [key: string]: unknown
}

export interface TransportRequest {
  /** Stable identifier for the operation issuing this request, of the form
   * `<ServiceClient>.<methodName>`. Middleware (e.g. tracing) can use this
   * to name a span or attach attributes; the underlying HTTP transport
   * ignores it.
   */
  operation: string
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
  url: string
  query?: Record<string, string | number | boolean | undefined>
  headers?: Record<string, string>
  body?: unknown
  options?: TransportOptions
}

export interface TransportResponse {
  status: number
  body: unknown
  /** Lowercased header names → values. Concrete transports must lowercase
   * keys so the client's error-dispatch lookup is case-insensitive.
   */
  headers: Record<string, string>
}

export interface Transport {
  request(req: TransportRequest): Promise<TransportResponse>
}

/** Thrown when the server returned a non-2xx status the client couldn't
 * match against the operation's declared errors — either no error is
 * declared for that status, or `X-Error-Type` didn't name any of them.
 * 401s are converted to `UnauthenticatedError` by the transport before
 * the client sees them, so they don't surface here.
 */
export class UnexpectedResponseError extends Error {
  readonly operation: string
  readonly status: number
  readonly body: unknown
  readonly headers: Record<string, string>
  constructor(operation: string, status: number, body: unknown, headers: Record<string, string>) {
    super(operation + ' -> ' + status)
    this.name = 'UnexpectedResponseError'
    this.operation = operation
    this.status = status
    this.body = body
    this.headers = headers
  }
}

/** Thrown by the transport for any 401. The auth middleware sits in front
 * of every route and isn't modelled per-operation, so 401 is never in an
 * operation's `errors: [...]` — we surface it as a typed error here.
 */
export class UnauthenticatedError extends Error {
  readonly operation: string
  constructor(operation: string) {
    super(operation + ' -> 401 Unauthorized')
    this.name = 'UnauthenticatedError'
    this.operation = operation
  }
}

/** A request whose body is streamed, whose response body is streamed,
 * or both. Everything a `TransportRequest` carries applies here too;
 * what is added is the framing and the outgoing stream.
 *
 * `streamEncoding` tells the transport how to frame each direction that
 * streams — the generator derives it from the shape of the `@streaming`
 * member, so the transport never has to guess from a content type:
 *
 *   - `'ndjson'` — one JSON value per line (`application/x-ndjson`).
 *     Outgoing: `JSON.stringify` each element, terminate each with a
 *     newline. Incoming: split on newlines, skip blank lines, and
 *     `JSON.parse` each one. The generated client applies the element
 *     schema on top of whatever is yielded here.
 *   - `'binary'` — the body verbatim
 *     (`application/octet-stream`), as `Uint8Array` chunks. Chunk
 *     boundaries carry no meaning in either direction.
 */
export type StreamEncoding = 'ndjson' | 'binary'

export interface StreamTransportRequest extends TransportRequest {
  /** Framing for the request body, when it streams. `undefined` means the
   * request body is an ordinary (unary) JSON body carried by `body`.
   */
  requestStreamEncoding?: StreamEncoding
  /** Framing the response body is expected in, when it streams.
   * `undefined` means an ordinary JSON response body.
   */
  responseStreamEncoding?: StreamEncoding
  /** The outgoing stream, present exactly when `requestStreamEncoding` is.
   * For `'ndjson'` these are the values to serialise, one per line; for
   * `'binary'`, `Uint8Array` chunks. Overrides `body`.
   */
  stream?: AsyncIterable<unknown>
}

export interface StreamTransportResponse {
  status: number
  /** Lowercased header names → values, as on `TransportResponse`. */
  headers: Record<string, string>
  /** The deframed response body, present exactly when the operation
   * streams its output and the status was 2xx. Elements are the values
   * `responseStreamEncoding` describes — already `JSON.parse`d for
   * `'ndjson'`, raw `Uint8Array` chunks for `'binary'`. The generated
   * client validates ndjson elements against the operation's schema.
   */
  stream?: AsyncIterable<unknown>
  /** The fully-read body, for a non-2xx response (so declared errors can
   * be parsed and thrown) or an operation with a unary response body.
   */
  body?: unknown
}

/** The streaming counterpart of `Transport`. A transport that backs a
 * service with streaming operations implements both; the generated client
 * takes whichever it needs.
 *
 * A streamed response commits its HTTP status before the first element is
 * pulled, so a failure that happens mid-stream cannot arrive as a status.
 * Such failures are modelled as members of the streamed union instead —
 * the protocol expects a terminal member (e.g. `completed` / `failed`) —
 * so `requestStream` rejecting means the request failed *before* the
 * stream started, and an error after that surfaces as an element or as an
 * exception thrown while iterating.
 */
export interface StreamTransport {
  requestStream(req: StreamTransportRequest): Promise<StreamTransportResponse>
}

/** Thrown when a streamed response was expected but the transport didn't
 * produce one (a transport bug, or a server that answered 2xx with a
 * non-streamed body). */
export class MissingStreamError extends Error {
  readonly operation: string
  constructor(operation: string) {
    super(operation + ' -> response did not carry a stream')
    this.name = 'MissingStreamError'
    this.operation = operation
  }
}

/** Validates each element of a deframed ndjson stream against the
 * operation's element schema, lazily — an element is parsed as it is
 * pulled, so a long-running stream doesn't buffer and a malformed element
 * fails at that element rather than silently truncating the stream. */
export const decodeStream = async function* <T>(
  source: AsyncIterable<unknown>,
  schema: { parse: (value: unknown) => T },
  operation: string,
): AsyncGenerator<T, void, undefined> {
  for await (const element of source) {
    try {
      yield schema.parse(element)
    } catch (err) {
      throw new StreamDecodeError(operation, element, err)
    }
  }
}

/** An empty stream, used when a request that declares a streamed input
 * arrives without one (e.g. a mock invoked with no stream). */
export const emptyStream = async function* (): AsyncGenerator<never, void, undefined> {}

/** Thrown while iterating a streamed response whose element failed the
 * operation's schema. Carries the offending element so a caller can log
 * what actually came over the wire. */
export class StreamDecodeError extends Error {
  readonly operation: string
  readonly element: unknown
  constructor(operation: string, element: unknown, cause: unknown) {
    super(operation + ' -> could not decode a stream element', { cause })
    this.name = 'StreamDecodeError'
    this.operation = operation
    this.element = element
  }
}


// --- Service clients ---

export class DirectoryClient {
  private readonly transport: Transport
  constructor(transport: Transport) {
    this.transport = transport
  }

  async getPerson(input: GetPersonInput, opts?: TransportOptions): Promise<GetPersonOutput> {
    const url = `/people/${encodeURIComponent(String(input.id))}`
    const query: Record<string, string | number | boolean | undefined> = {}
    if (input.verbose !== undefined) query['verbose'] = input.verbose
    const res = await this.transport.request({
      operation: 'DirectoryClient.getPerson',
      method: 'GET',
      url,
      query,
      body: undefined,
      options: opts,
    })
    if (res.status >= 200 && res.status < 300) {
      const raw: Record<string, unknown> = { ...(GetPersonOutputSchema.omit({ 'code': true, 'trace': true }).parse(res.body) as Record<string, unknown>) }
      if (res.headers['x-trace'] !== undefined) {
        raw['trace'] = res.headers['x-trace']
      }
      raw['code'] = res.status
      return GetPersonOutputSchema.parse(raw) as GetPersonOutput
    }
    if (res.status === 404) {
      throw new NotFoundError(NotFoundSchema.parse(res.body))
    }
    if (res.status === 409) {
      const errorType = res.headers['x-error-type']
      if (errorType === 'Conflict') throw new ConflictError(ConflictSchema.parse(res.body))
      if (errorType === 'AlreadyExists') throw new AlreadyExistsError(AlreadyExistsSchema.parse(res.body))
    }
    throw new UnexpectedResponseError('DirectoryClient.getPerson', res.status, res.body, res.headers)
  }

  /** No input, no output. */
  async ping(opts?: TransportOptions): Promise<void> {
    const url = `/ping`
    const res = await this.transport.request({
      operation: 'DirectoryClient.ping',
      method: 'POST',
      url,
      body: undefined,
      options: opts,
    })
    if (res.status >= 200 && res.status < 300) {
      return undefined
    }
    if (res.status === 404) {
      throw new NotFoundError(NotFoundSchema.parse(res.body))
    }
    throw new UnexpectedResponseError('DirectoryClient.ping', res.status, res.body, res.headers)
  }

  async putPerson(input: PutPersonInput, opts?: TransportOptions): Promise<void> {
    const url = `/people/${encodeURIComponent(String(input.id))}`
    const headers: Record<string, string> = {}
    if (input.ifMatch !== undefined) headers['if-match'] = String(input.ifMatch)
    const res = await this.transport.request({
      operation: 'DirectoryClient.putPerson',
      method: 'PUT',
      url,
      headers,
      body: input.person,
      options: opts,
    })
    if (res.status >= 200 && res.status < 300) {
      return undefined
    }
    if (res.status === 404) {
      throw new NotFoundError(NotFoundSchema.parse(res.body))
    }
    throw new UnexpectedResponseError('DirectoryClient.putPerson', res.status, res.body, res.headers)
  }

  async search(input: SearchInput, opts?: TransportOptions): Promise<SearchOutput> {
    const url = `/search`
    const query: Record<string, string | number | boolean | undefined> = {}
    if (input.q !== undefined) query['q'] = String(input.q)
    const res = await this.transport.request({
      operation: 'DirectoryClient.search',
      method: 'GET',
      url,
      query,
      body: undefined,
      options: opts,
    })
    if (res.status >= 200 && res.status < 300) {
      return SearchOutputSchema.parse(res.body)
    }
    if (res.status === 404) {
      throw new NotFoundError(NotFoundSchema.parse(res.body))
    }
    throw new UnexpectedResponseError('DirectoryClient.search', res.status, res.body, res.headers)
  }
}

export class FeedClient {
  private readonly transport: Transport
  private readonly streamTransport: StreamTransport
  constructor(transport: Transport, streamTransport: StreamTransport) {
    this.transport = transport
    this.streamTransport = streamTransport
  }

  /**
   * Streams ndjson in both directions.
   * Streams `incoming` to the server as newline-delimited `FeedEvent` values.
   * Resolves once the response status is known; `outgoing` then yields newline-delimited `FeedEvent` values lazily, so iterate it to consume the response.
   */
  async echo(input: EchoInput, opts?: TransportOptions): Promise<EchoOutput> {
    const url = `/echo`
    const res = await this.streamTransport.requestStream({
      operation: 'FeedClient.echo',
      method: 'POST',
      url,
      body: undefined,
      requestStreamEncoding: 'ndjson',
      stream: input.incoming,
      responseStreamEncoding: 'ndjson',
      options: opts,
    })
    if (res.status >= 200 && res.status < 300) {
      if (res.stream === undefined) {
        throw new MissingStreamError('FeedClient.echo')
      }
      const raw: Record<string, unknown> = {}
      raw['outgoing'] = decodeStream(res.stream, FeedEventSchema, 'FeedClient.echo')
      return raw as EchoOutput
    }
    if (res.status === 404) {
      throw new NotFoundError(NotFoundSchema.parse(res.body))
    }
    throw new UnexpectedResponseError('FeedClient.echo', res.status, res.body, res.headers)
  }

  /** A unary operation on a streaming service. */
  async plain(opts?: TransportOptions): Promise<PlainOutput> {
    const url = `/plain`
    const res = await this.transport.request({
      operation: 'FeedClient.plain',
      method: 'GET',
      url,
      body: undefined,
      options: opts,
    })
    if (res.status >= 200 && res.status < 300) {
      return PlainOutputSchema.parse(res.body)
    }
    if (res.status === 404) {
      throw new NotFoundError(NotFoundSchema.parse(res.body))
    }
    throw new UnexpectedResponseError('FeedClient.plain', res.status, res.body, res.headers)
  }

  /**
   * Streams raw bytes in.
   * Streams `body` to the server as raw bytes.
   */
  async upload(input: UploadInput, opts?: TransportOptions): Promise<UploadOutput> {
    const url = `/upload/${encodeURIComponent(String(input.id))}`
    const res = await this.streamTransport.requestStream({
      operation: 'FeedClient.upload',
      method: 'POST',
      url,
      body: undefined,
      requestStreamEncoding: 'binary',
      stream: input.body,
      options: opts,
    })
    if (res.status >= 200 && res.status < 300) {
      return UploadOutputSchema.parse(res.body)
    }
    if (res.status === 404) {
      throw new NotFoundError(NotFoundSchema.parse(res.body))
    }
    throw new UnexpectedResponseError('FeedClient.upload', res.status, res.body, res.headers)
  }

  /**
   * Streams ndjson out, with a header alongside the stream.
   * Resolves once the response status is known; `events` then yields newline-delimited `FeedEvent` values lazily, so iterate it to consume the response.
   */
  async watch(input: WatchInput, opts?: TransportOptions): Promise<WatchOutput> {
    const url = `/watch/${encodeURIComponent(String(input.id))}`
    const query: Record<string, string | number | boolean | undefined> = {}
    if (input.since !== undefined) query['since'] = input.since.toISOString()
    const res = await this.streamTransport.requestStream({
      operation: 'FeedClient.watch',
      method: 'GET',
      url,
      query,
      body: undefined,
      responseStreamEncoding: 'ndjson',
      options: opts,
    })
    if (res.status >= 200 && res.status < 300) {
      if (res.stream === undefined) {
        throw new MissingStreamError('FeedClient.watch')
      }
      const raw: Record<string, unknown> = {}
      if (res.headers['x-session'] !== undefined) {
        raw['session'] = z.string().parse(res.headers['x-session'])
      }
      raw['events'] = decodeStream(res.stream, FeedEventSchema, 'FeedClient.watch')
      return raw as WatchOutput
    }
    if (res.status === 404) {
      throw new NotFoundError(NotFoundSchema.parse(res.body))
    }
    throw new UnexpectedResponseError('FeedClient.watch', res.status, res.body, res.headers)
  }
}


// --- Storybook mock server ---

/** A request as seen by the mock server: the URL path already has any
 * proxy prefix stripped, `pathParams` holds decoded `@httpLabel`
 * values, `query` the parsed query string, `body` the parsed JSON body. */
export interface MockRequest {
  method: string
  path: string
  pathParams: Record<string, string>
  query: Record<string, string | undefined>
  body: unknown
  /** The deframed request body, for an operation that streams its input.
   * Elements are `JSON.parse`d values for an ndjson stream and
   * `Uint8Array` chunks for a binary one — the same shape the streaming
   * transport yields, so a mock and a real server see the same thing. */
  stream?: AsyncIterable<unknown>
}

export interface MockResponse {
  status: number
  body: unknown
  headers: Record<string, string>
  /** Set instead of `body` when the operation streams its output; the
   * adapter frames these elements per `streamEncoding`. */
  stream?: AsyncIterable<unknown>
  /** Framing for `stream`, mirroring `StreamEncoding` on the transport. */
  streamEncoding?: 'ndjson' | 'binary'
}

/** One URI path segment of an operation's route: a literal or a
 * `@httpLabel` capture. */
export type MockUriSegment = { readonly literal: string } | { readonly label: string }

/** A single operation's route + codecs. `decodeInput` turns a matched
 * request into the operation's typed input; `encodeBody` extracts the
 * HTTP response body from the typed output. */
export interface MockOperation<Handlers> {
  readonly key: keyof Handlers & string
  readonly method: string
  readonly segments: readonly MockUriSegment[]
  readonly decodeInput: (req: MockRequest) => unknown
  readonly encodeBody: (output: unknown) => unknown
  /** Framing of this operation's streamed output, when it streams one.
   * `undefined` for an ordinary unary operation. */
  readonly responseStreamEncoding?: 'ndjson' | 'binary'
  /** Pulls the streamed member out of a handler's returned output, for
   * an operation that streams its output. */
  readonly encodeStream?: (output: unknown) => AsyncIterable<unknown>
}

export interface MockServiceDescriptor<Handlers> {
  readonly serviceName: string
  readonly operations: readonly MockOperation<Handlers>[]
}

/** Thrown from a handler to return an arbitrary HTTP status/body that
 * isn't one of the operation's declared, typed errors (e.g. a 503 to
 * exercise a generic failure path). */
export class MockHttpError extends Error {
  readonly status: number
  readonly body: unknown
  constructor(status: number, body: unknown = { message: 'Error' }) {
    super('MockHttpError ' + status)
    this.name = 'MockHttpError'
    this.status = status
    this.body = body
  }
}

/** A matched, ready-to-run mock operation: everything the shared adapter
 * needs to invoke one handler and encode its result. */
export interface MockMatch {
  run: (req: MockRequest) => Promise<MockResponse>
}

/** A bound service mock: a matcher from HTTP method + path to a runnable
 * operation, or `null` when this service handles no such route. */
export interface BoundMockService {
  serviceName: string
  match: (method: string, path: string) => MockMatch | null
}

const matchSegments = (
  segments: readonly MockUriSegment[],
  path: string,
): Record<string, string> | null => {
  const parts = path.split('/').filter((p) => p.length > 0)
  if (parts.length !== segments.length) return null
  const pathParams: Record<string, string> = {}
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i]
    if ('literal' in seg) {
      if (seg.literal !== parts[i]) return null
    }
    else {
      pathParams[seg.label] = decodeURIComponent(parts[i])
    }
  }
  return pathParams
}

/** Binds a service descriptor to a partial set of handlers, producing a
 * matcher. An unimplemented operation that gets called throws, so stories
 * only implement the operations they exercise. A thrown generated error
 * (`XxxError`) is encoded to its declared status + `x-error-type`; a
 * `MockHttpError` to its status/body; anything else re-throws. */
export const mockService = <Handlers>(
  descriptor: MockServiceDescriptor<Handlers>,
  handlers: Partial<Handlers>,
): BoundMockService => ({
  serviceName: descriptor.serviceName,
  match: (method, path) => {
    for (const op of descriptor.operations) {
      if (op.method !== method) continue
      const pathParams = matchSegments(op.segments, path)
      if (pathParams === null) continue
      const handler = handlers[op.key] as
        | ((input: unknown) => unknown | Promise<unknown>)
        | undefined
      return {
        run: async (req): Promise<MockResponse> => {
          if (handler === undefined) {
            throw new Error(descriptor.serviceName + '.' + op.key + ' called but no mock handler was provided')
          }
          const input = op.decodeInput({ ...req, pathParams })
          try {
            const output = await handler(input)
            if (op.encodeStream !== undefined) {
              return {
                status: 200,
                body: op.encodeBody(output),
                headers: {},
                stream: op.encodeStream(output),
                streamEncoding: op.responseStreamEncoding,
              }
            }
            return { status: 200, body: op.encodeBody(output), headers: {} }
          } catch (err) {
            if (err instanceof MockHttpError) {
              return { status: err.status, body: err.body, headers: {} }
            }
            if (isTypedMockError(err)) {
              return { status: err.status, body: err.payload, headers: { 'x-error-type': err.errorType } }
            }
            throw err
          }
        },
      }
    }
    return null
  },
})

interface TypedMockError {
  status: number
  errorType: string
  payload: unknown
}

const isTypedMockError = (err: unknown): err is TypedMockError =>
  err instanceof Error &&
  typeof (err as { status?: unknown }).status === 'number' &&
  typeof (err as { errorType?: unknown }).errorType === 'string' &&
  'payload' in err

/** Routes a request across several bound services, returning the first
 * match. Stories pass the mocks for whichever services a screen touches. */
export const mockServices = (
  ...services: readonly BoundMockService[]
): ((method: string, path: string) => MockMatch | null) =>
  (method, path) => {
    for (const svc of services) {
      const m = svc.match(method, path)
      if (m !== null) return m
    }
    return null
  }

export interface DirectoryHandlers {
  getPerson(input: GetPersonInput): GetPersonOutput | Promise<GetPersonOutput>
  /** No input, no output. */
  ping(): void | Promise<void>
  putPerson(input: PutPersonInput): void | Promise<void>
  search(input: SearchInput): SearchOutput | Promise<SearchOutput>
}

export const DirectoryMock: MockServiceDescriptor<DirectoryHandlers> = {
  serviceName: 'Directory',
  operations: [
    {
      key: 'getPerson',
      method: 'GET',
      segments: [{ literal: 'people' }, { label: 'id' }],
      decodeInput: (req) => {
        const raw: Record<string, unknown> = {}
        raw['id'] = req.pathParams['id']
        if (req.query['verbose'] !== undefined) {
          raw['verbose'] = (req.query['verbose'] as string === 'true')
        }
        return GetPersonInputSchema.parse(raw) as GetPersonInput
      },
      encodeBody: (output) => { const { code: _code, trace: _trace, ...body } = output as Record<string, unknown>; return body },
    },
    {
      key: 'ping',
      method: 'POST',
      segments: [{ literal: 'ping' }],
      decodeInput: () => undefined,
      encodeBody: () => ({}),
    },
    {
      key: 'putPerson',
      method: 'PUT',
      segments: [{ literal: 'people' }, { label: 'id' }],
      decodeInput: (req) => {
        const raw: Record<string, unknown> = {}
        raw['id'] = req.pathParams['id']
        raw['person'] = req.body
        return PutPersonInputSchema.parse(raw) as PutPersonInput
      },
      encodeBody: () => ({}),
    },
    {
      key: 'search',
      method: 'GET',
      segments: [{ literal: 'search' }],
      decodeInput: (req) => {
        const raw: Record<string, unknown> = {}
        if (req.query['q'] !== undefined) {
          raw['q'] = req.query['q'] as string
        }
        return SearchInputSchema.parse(raw) as SearchInput
      },
      encodeBody: (output) => output,
    },
  ],
}

export interface FeedHandlers {
  /** Streams ndjson in both directions. */
  echo(input: EchoInput): EchoOutput | Promise<EchoOutput>
  /** A unary operation on a streaming service. */
  plain(): PlainOutput | Promise<PlainOutput>
  /** Streams raw bytes in. */
  upload(input: UploadInput): UploadOutput | Promise<UploadOutput>
  /** Streams ndjson out, with a header alongside the stream. */
  watch(input: WatchInput): WatchOutput | Promise<WatchOutput>
}

export const FeedMock: MockServiceDescriptor<FeedHandlers> = {
  serviceName: 'Feed',
  operations: [
    {
      key: 'echo',
      method: 'POST',
      segments: [{ literal: 'echo' }],
      decodeInput: (req) => {
        const raw: Record<string, unknown> = {}
        const decoded = EchoInputSchema.parse(raw)
        return {
          ...decoded,
          incoming: decodeStream((req.stream ?? emptyStream()), FeedEventSchema, 'Echo'),
        }
      },
      encodeBody: () => undefined,
      responseStreamEncoding: 'ndjson',
      encodeStream: (output) => (output as Record<string, unknown>)['outgoing'] as AsyncIterable<unknown>,
    },
    {
      key: 'plain',
      method: 'GET',
      segments: [{ literal: 'plain' }],
      decodeInput: () => undefined,
      encodeBody: (output) => output,
    },
    {
      key: 'upload',
      method: 'POST',
      segments: [{ literal: 'upload' }, { label: 'id' }],
      decodeInput: (req) => {
        const raw: Record<string, unknown> = {}
        raw['id'] = req.pathParams['id']
        const decoded = UploadInputSchema.parse(raw)
        return {
          ...decoded,
          body: (req.stream ?? emptyStream()) as AsyncIterable<Uint8Array>,
        }
      },
      encodeBody: (output) => output,
    },
    {
      key: 'watch',
      method: 'GET',
      segments: [{ literal: 'watch' }, { label: 'id' }],
      decodeInput: (req) => {
        const raw: Record<string, unknown> = {}
        raw['id'] = req.pathParams['id']
        if (req.query['since'] !== undefined) {
          raw['since'] = req.query['since'] as string
        }
        return WatchInputSchema.parse(raw) as WatchInput
      },
      encodeBody: () => undefined,
      responseStreamEncoding: 'ndjson',
      encodeStream: (output) => (output as Record<string, unknown>)['events'] as AsyncIterable<unknown>,
    },
  ],
}

