/** Out-of-the-box transports for clients generated by `smithy-ts-codegen`.
 *
 * The generated file stays self-contained — it declares its own `Transport` /
 * `StreamTransport` interfaces and imports nothing from here. This package's
 * types are structural copies of those, so a transport built here satisfies a
 * generated client by shape:
 *
 * ```ts
 * import { fetchTransport } from '@polyvariant/smithy-ts-runtime'
 * import { DirectoryClient, FeedClient } from './generated.js'
 *
 * const transport = fetchTransport({ baseUrl: '/api' })
 * const directory = new DirectoryClient(transport)
 * const feed = new FeedClient(transport, transport)   // streaming operations
 * ```
 */

export { fetchTransport } from './fetch.js'
export type { FetchTransportOptions } from './fetch.js'

export {
  around,
  aroundStream,
  chain,
  chainStream,
  interceptorStack,
  mapRequest,
  tap,
  withHeaders,
} from './middleware.js'
export type { Middleware, StreamMiddleware } from './middleware.js'

export {
  asyncIterableToReadable,
  collectBytes,
  decodeNdjson,
  encodeBinary,
  encodeNdjson,
  readableToAsyncIterable,
} from './ndjson.js'

export { NdjsonParseError, StreamRequestError, UnauthenticatedError } from './errors.js'

// Exported so a hand-rolled transport can honor `@lossless` members: plain
// `JSON.parse` / `JSON.stringify` cannot, and using them silently rounds a
// value the model declares must survive exactly.
export { parseLossless, stringifyLossless } from './json.js'

export type {
  FullTransport,
  HttpMethod,
  StreamEncoding,
  StreamTransport,
  StreamTransportRequest,
  StreamTransportResponse,
  Transport,
  TransportOptions,
  TransportRequest,
  TransportResponse,
} from './types.js'
